version: "3"

services:
  db:
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
  api:
    image: apollo-objekts
    environment:
      - DB_NAME
      - DB_PORT
      - DB_HOST
      - DB_PASS
      - GQL_PORT
    ports:
      - "${GQL_PORT}:${GQL_PORT}"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    image: apollo-objekts
    restart: always
    environment:
      - DB_NAME
      - DB_PORT
      - DB_HOST
      - DB_PASS
      - REDIS_HOST
      - REDIS_PORT
    command: ["sqd", "process:prod"]
    depends_on:
      - db
      - cache
  cache:
    image: redis:7.2-alpine
    depends_on:
      - db
    restart: always
    environment:
      - REDIS_PORT
      - REDIS_PASSWORD
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 60 100 --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local
