version: "3"

services:
  db:
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
  # api:
  #   build:
  #     context: .
  #     dockerfile: squid.Dockerfile
  #   environment:
  #     - DB_NAME
  #     - DB_PORT=5432
  #     - DB_HOST=db
  #     - DB_PASS
  #     - GQL_PORT
  #   ports:
  #     - "${GQL_PORT}:${GQL_PORT}"
  #   command: ["sqd", "serve:prod"]
  #   depends_on:
  #     - db
  processor:
    build:
      context: .
      dockerfile: squid.Dockerfile
    restart: always
    environment:
      - DB_NAME
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS
      - DB_READ_USER
      - DB_READ_PASS
    command: ["sqd", "process:prod"]
    depends_on:
      - db
  # proxy:
  #   build:
  #     context: .
  #     dockerfile: proxy.Dockerfile
  #   restart: always
  #   environment:
  #     - DB_NAME
  #     - DB_PORT=5432
  #     - DB_HOST=db
  #     - DB_PASS
  #     - PROXY_PORT
  #   ports:
  #     - "${PROXY_PORT}:${PROXY_PORT}"
  #   depends_on:
  #     - db
volumes:
  db:
    driver: local
