version: "3"

services:
  db:
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
      # Uncomment for logging all SQL statements
      # command: ["postgres", "-c", "log_statement=all"]
  api:
    build: .
    environment:
      - DB_NAME
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS
      - GQL_PORT
    ports:
      - "${GQL_PORT}:${GQL_PORT}"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
  processor:
    build: .
    restart: always
    environment:
      - DB_NAME
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS
      - REDIS_HOST
      - REDIS_PORT
    command: ["sqd", "process:prod"]
    depends_on:
      - db
volumes:
  db:
    driver: local
